[package]
name = "parui"
description = "Simple TUI frontend for paru."
version = "0.1.2"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Vonr/parui"
repository = "https://github.com/Vonr/parui"
keywords = ["tui", "terminal", "frontend", "paru"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
crossterm = "0.23.2"
tui = { version = "0.18", features = ["crossterm"] }

